describe ('UnHappyPath- Direccion UI', ()=> {
    it('Direccion UI', ()=> {
cy.visit('https://ticketazo.com.ar/auth/login')    
cy.get('[data-cy="btn-register-user"]').click() 
cy.get('[data-cy="input-nombres"]').type('franco')
cy.get('[data-cy="input-apellido"]').type('vinci')
cy.get('[data-cy="input-telefono"]').type('1143587721')
cy.get('[data-cy="input-dni"]').type('44751797')
cy.get('[data-cy="select-provincia"]').click()
cy.contains('Ciudad Autónoma de Buenos Aires').click()
cy.get('[data-cy="select-provincia"]').should('have.value', 'Ciudad Autónoma de Buenos Aires')
cy.get('[data-cy="select-localidad"]').click()
cy.contains('Mataderos').click()
cy.get('[data-cy="select-localidad"]').should('have.value', 'Mataderos')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('dd').click().type('10')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('mm').click().type('04')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('aaaa').click().type('2003')
cy.get('[data-cy="input-email"]').type('francovinci@gmail.com')
cy.get('[data-cy="input-confirmar-email"]').type('francovinci@gmail.com')
cy.get('[data-cy="input-password"]').type('francovinci1234')
cy.get('[data-cy="input-repetir-password"]').type('francovinci1234')
cy.get('[data-cy="btn-registrarse"]').click()
cy.contains('La contraseña debe tener al menos 8 caracteres, incluyendo mayúsculas, minúsculas, números y símbolos.').should('be.visible')
//cy.get('#username').type('frannkiss') //cuando ponemos # estamos llamando a un id 
//cy.get('.shadow-sm').eq(3).type('contraseña') //usamos el eq para marcar que elemento queremos que compartna clase o id, quiero el q tiene esta clase pero el 3 que aparece visualmente de arriba a abajo

})
})
describe ('HappyPath- Direccion UI', ()=> {
    it('Direccion UI', ()=> {
cy.visit('https://ticketazo.com.ar/auth/login')    
cy.get('[data-cy="btn-register-user"]').click() 
cy.get('[data-cy="input-nombres"]').type('franco')
cy.get('[data-cy="input-apellido"]').type('vinci')
cy.get('[data-cy="input-telefono"]').type('1143587721')
cy.get('[data-cy="input-dni"]').type('44751797')
cy.get('[data-cy="select-provincia"]').click()
cy.contains('Ciudad Autónoma de Buenos Aires').click()
cy.get('[data-cy="select-provincia"]').should('have.value', 'Ciudad Autónoma de Buenos Aires')
cy.get('[data-cy="select-localidad"]').click()
cy.contains('Mataderos').click()
cy.get('[data-cy="select-localidad"]').should('have.value', 'Mataderos')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('dd').click().type('10')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('mm').click().type('04')
cy.get('[data-cy="input-fecha-nacimiento"]').click()
cy.contains('aaaa').click().type('2003')
cy.get('[data-cy="input-email"]').type('francovinci@gmail.com')
cy.get('[data-cy="input-confirmar-email"]').type('francovinci@gmail.com')
cy.get('[data-cy="input-password"]').type('Francovi1234@')
cy.get('[data-cy="input-repetir-password"]').type('Francovi1234@')
cy.get('[data-cy="btn-registrarse"]').click()

    })
})